---
#
# Ansible playbook to manage updating SSL certificates
# for Apache and Nginx on EL systems
#

- name: Update Webserver SSL Certificates
  hosts: all
  remote_user: root
  roles:
    - {role: sslcerts}
